### ISSUE TITLE
Can you upgrade this plugin to make it compatible with IntelliJ IDEA 2024.2.x

### ISSUE THREAD

**Issue by frikit** [tommilata/intelliroutes#22]
<img width="368" alt="Screenshot 2024-08-07 at 11 25 09" src="https://github.com/user-attachments/assets/6f097c8e-2180-43c8-a2a3-f00da32dd372">

Intellij version:
IntelliJ IDEA 2024.2 (Community Edition)
Build #IC-242.20224.300, built on August 6, 2024
Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)

**Comment by stephane303** [comment]
@tommilata thank you to check this, it's a very usefull tool ;-)

**Comment by tommilata** [comment]
Hi all, thanks for reminding me and sorry to keep you waiting, I've been busy with life lately.

I've pushed a new [release](https://plugins.jetbrains.com/plugin/10053-play-2-routes/versions/stable/603511) now, it should be in the marketplace within a few working days.

**Comment by tommilata** [comment]
This is done now.
