### ISSUE TITLE
Support for new upcoming Intellij Idea 242.*

### ISSUE THREAD

**Issue by frikit** [tommilata/intelliroutes#26]
Pretty much the title is the issues: Support for new upcoming Intellij Idea 242.*
We started to use EAP version because of scala 3 support, and only couple plugins dont work, i am going and raising in each repo an issue. I am happy to help if you have some form of documentation or steps for testing i can use to raise a PR.

Thanks

**Comment by tommilata** [comment]
Hi, thanks for flagging. Been busy with life lately.

Just releasing an upgrade, it should be available within a few days.

**Comment by tommilata** [comment]
https://plugins.jetbrains.com/plugin/10053-play-2-routes/edit/versions/stable/634235
